name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Export web build
        run: npx expo export:web
        env:
          EXPO_PUBLIC_TOOLKIT_URL: ${{ secrets.EXPO_PUBLIC_TOOLKIT_URL }}
          CI: true
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: dist/
