name: Build Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Setup Rork Toolkit SDK mock
        run: |
          mkdir -p node_modules/@rork-ai/toolkit-sdk/metro
          echo "module.exports = { withRorkMetro: (config) => config };" > node_modules/@rork-ai/toolkit-sdk/metro/index.js
          mkdir -p node_modules/@rork-ai/toolkit-sdk
          echo '{"name":"@rork-ai/toolkit-sdk","version":"1.0.0"}' > node_modules/@rork-ai/toolkit-sdk/package.json
      
      - name: Install dependencies
        run: bun install
      
      - name: Create env file
        run: |
          echo "EXPO_PUBLIC_TOOLKIT_URL=${{ secrets.EXPO_PUBLIC_TOOLKIT_URL }}" > .env
      
      - name: Export web build
        run: bun run export
        env:
          CI: true
          NODE_ENV: production
      
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          dangerous-clean-slate: false
